2018-04-10 10:45:43.168 [error] <0.1767.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.1772.0> exit with reason normal in context child_terminated
2018-04-10 10:47:45.455 [error] <0.387.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.392.0> exit with reason normal in context child_terminated
2018-04-10 10:48:38.319 [error] <0.392.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.397.0> exit with reason normal in context child_terminated
2018-04-10 11:07:12.861 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
2018-04-10 11:07:45.777 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
2018-04-10 11:08:14.499 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.210.0> exit with reason normal in context child_terminated
2018-04-10 11:09:26.902 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.210.0> exit with reason normal in context child_terminated
2018-04-10 11:10:33.048 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:11:27.576 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:15:09.254 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:16:25.008 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:17:39.607 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:19:27.367 [error] <0.204.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.209.0> exit with reason normal in context child_terminated
2018-04-10 11:23:46.118 [error] <0.213.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.218.0> exit with reason normal in context child_terminated
2018-04-10 11:24:36.691 [error] <0.213.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.218.0> exit with reason normal in context child_terminated
2018-04-10 11:25:16.343 [error] <0.204.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.209.0> exit with reason normal in context child_terminated
2018-04-10 11:26:28.902 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:27:10.778 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:29:48.029 [error] <0.219.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.224.0> exit with reason normal in context child_terminated
2018-04-10 11:30:03.301 [error] <0.505.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.505.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2076037934.3389259782.152271>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:30:08.302 [error] <0.506.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.506.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2076037934.3389259782.152272>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:30:13.303 [error] <0.507.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.507.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2076037934.3389259782.152277>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:31:29.460 [error] <0.214.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.219.0> exit with reason normal in context child_terminated
2018-04-10 11:31:41.645 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.210.0> exit with reason normal in context child_terminated
2018-04-10 11:31:44.805 [error] <0.491.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2952308943.3926130690.156577>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:31:49.806 [error] <0.492.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.492.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2952308943.3926130694.156749>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:31:54.807 [error] <0.493.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.493.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.2952308943.3926130694.156755>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:33:07.653 [error] <0.214.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.219.0> exit with reason normal in context child_terminated
2018-04-10 11:33:21.219 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.210.0> exit with reason normal in context child_terminated
2018-04-10 11:33:27.910 [error] <0.491.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.3323765014.168558594.29497>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:33:32.911 [error] <0.492.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.492.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.3323765014.168558594.29502>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:34:12.712 [error] <0.214.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.219.0> exit with reason normal in context child_terminated
2018-04-10 11:34:16.879 [error] <0.500.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.500.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.3205166336.1510735878.16463>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:34:21.880 [error] <0.501.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.501.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.3205166336.1510735878.16473>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:34:26.880 [error] <0.502.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.502.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.3205166336.1510735878.16483>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:34:43.102 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:34:52.530 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.210.0> exit with reason normal in context child_terminated
2018-04-10 11:34:56.464 [error] <0.491.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.491.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.1317325850.3389784065.226836>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:35:01.464 [error] <0.492.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.492.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.1317325850.3389784065.226837>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:35:06.465 [error] <0.493.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.493.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.1317325850.3389784065.226843>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:36:10.012 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:36:13.386 [error] <0.806.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.806.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.1828257336.2047344641.214964>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:36:18.380 [error] <0.807.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.807.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.1828257336.2047344641.214969>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:36:53.174 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:36:54.805 [error] <0.806.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.806.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.4055000106.2584477699.14023>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:36:59.806 [error] <0.807.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.807.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.4055000106.2584477699.14032>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:37:22.432 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:37:23.849 [error] <0.806.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.806.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.80143530.1510473730.257484>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:37:28.856 [error] <0.807.0>@eradius_server:run_handler:264 CRASH REPORT Process <0.807.0> with 0 neighbours crashed with reason: bad argument in call to erlang:phash2(#Ref<0.80143530.1510473730.257487>, 0) in eradius_server:run_handler/4 line 264
2018-04-10 11:39:23.424 [error] <0.520.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.525.0> exit with reason normal in context child_terminated
2018-04-10 11:39:46.659 [error] <0.213.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.218.0> exit with reason normal in context child_terminated
2018-04-10 11:40:07.125 [error] <0.204.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.209.0> exit with reason normal in context child_terminated
2018-04-10 11:42:09.106 [error] <0.213.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.218.0> exit with reason normal in context child_terminated
2018-04-10 11:43:09.643 [error] <0.521.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.526.0> exit with reason normal in context child_terminated
2018-04-10 11:44:29.594 [error] <0.1789.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.1794.0> exit with reason normal in context child_terminated
2018-04-10 11:46:58.878 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
